In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../model/coordinates_with_distances.csv')
df

,city_code,city,uf,lat,long,radiance,geometry,distance_to_city
0,1101450,Parecis,RO,-12.004167,-61.333332,0.226823,POINT (-61.333332384 -12.004167362700002),0.317654
1,1101450,Parecis,RO,-12.004167,-61.329166,0.252866,POINT (-61.3291657173 -12.004167362700002),0.321134
2,1101450,Parecis,RO,-12.004167,-61.324999,0.221371,POINT (-61.3249990506 -12.004167362700002),0.324630
3,1101450,Parecis,RO,-12.004167,-61.320832,0.203252,POINT (-61.3208323839 -12.004167362700002),0.328142
4,1101450,Parecis,RO,-12.004167,-61.316666,0.213139,POINT (-61.3166657172 -12.004167362700002),0.331669
...,...,...,...,...,...,...,...,...
1212028,5204250,Cachoeira Dourada,GO,-18.612501,-49.741666,0.273667,POINT (-49.74166562459999 -18.612500748900004),0.297570
1212029,5204250,Cachoeira Dourada,GO,-18.612501,-49.737499,0.284952,POINT (-49.73749895789999 -18.612500748900004),0.293784
1212030,5204250,Cachoeira Dourada,GO,-18.612501,-49.733332,0.268688,POINT (-49.73333229119999 -18.612500748900004),0.290009
1212031,5204250,Cachoeira Dourada,GO,-18.612501,-49.729166,0.248612,POINT (-49.729165624499984 -18.612500748900004),0.286244
1212032,5204250,Cachoeira Dourada,GO,-18.616667,-49.737499,0.266826,POINT (-49.73749895789999 -18.61666741560001),0.295560

In [3]:
# remove < 0
df = df[df['radiance'] > 0]
df

,city_code,city,uf,lat,long,radiance,geometry,distance_to_city
0,1101450,Parecis,RO,-12.004167,-61.333332,0.226823,POINT (-61.333332384 -12.004167362700002),0.317654
1,1101450,Parecis,RO,-12.004167,-61.329166,0.252866,POINT (-61.3291657173 -12.004167362700002),0.321134
2,1101450,Parecis,RO,-12.004167,-61.324999,0.221371,POINT (-61.3249990506 -12.004167362700002),0.324630
3,1101450,Parecis,RO,-12.004167,-61.320832,0.203252,POINT (-61.3208323839 -12.004167362700002),0.328142
4,1101450,Parecis,RO,-12.004167,-61.316666,0.213139,POINT (-61.3166657172 -12.004167362700002),0.331669
...,...,...,...,...,...,...,...,...
1212028,5204250,Cachoeira Dourada,GO,-18.612501,-49.741666,0.273667,POINT (-49.74166562459999 -18.612500748900004),0.297570
1212029,5204250,Cachoeira Dourada,GO,-18.612501,-49.737499,0.284952,POINT (-49.73749895789999 -18.612500748900004),0.293784
1212030,5204250,Cachoeira Dourada,GO,-18.612501,-49.733332,0.268688,POINT (-49.73333229119999 -18.612500748900004),0.290009
1212031,5204250,Cachoeira Dourada,GO,-18.612501,-49.729166,0.248612,POINT (-49.729165624499984 -18.612500748900004),0.286244
1212032,5204250,Cachoeira Dourada,GO,-18.616667,-49.737499,0.266826,POINT (-49.73749895789999 -18.61666741560001),0.295560

In [4]:
df['rank'] = df.groupby('city_code')['distance_to_city'].rank()
nearest = df[df['rank'] <= 100]
nearest

C:\Users\Pedro\AppData\Local\Temp\ipykernel_6084\1720358833.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rank'] = df.groupby('city_code')['distance_to_city'].rank()

,city_code,city,uf,lat,long,radiance,geometry,distance_to_city,rank
3186,1101450,Parecis,RO,-12.158334,-61.604166,0.235929,POINT (-61.6041657195 -12.158334030600004),0.022360,89.0
3187,1101450,Parecis,RO,-12.158334,-61.599999,0.252750,POINT (-61.5999990528 -12.158334030600004),0.021586,83.0
3188,1101450,Parecis,RO,-12.158334,-61.595832,0.253744,POINT (-61.5958323861 -12.158334030600004),0.021602,85.0
3189,1101450,Parecis,RO,-12.158334,-61.591666,0.231304,POINT (-61.5916657194 -12.158334030600004),0.022406,90.0
3303,1101450,Parecis,RO,-12.162501,-61.612499,0.235071,POINT (-61.61249905289999 -12.162500697300004),0.022594,91.0
...,...,...,...,...,...,...,...,...,...
1211139,5204250,Cachoeira Dourada,GO,-18.508334,-49.470832,1.707905,POINT (-49.4708322891 -18.508334081400008),0.019299,67.0
1211140,5204250,Cachoeira Dourada,GO,-18.508334,-49.466666,1.696757,POINT (-49.4666656224 -18.508334081400008),0.019761,72.0
1211141,5204250,Cachoeira Dourada,GO,-18.508334,-49.462499,1.550770,POINT (-49.4624989557 -18.508334081400008),0.021055,81.0
1211142,5204250,Cachoeira Dourada,GO,-18.508334,-49.458332,0.853822,POINT (-49.458332289 -18.508334081400008),0.023040,98.0
1211205,5204250,Cachoeira Dourada,GO,-18.512501,-49.470832,0.648533,POINT (-49.4708322891 -18.512500748099995),0.023465,100.0

In [5]:
nearest.to_csv('../model/nearest_nightlights_per_city.csv', index=False)